### ISSUE TITLE
[Bug]: Can't filter for _start

### ISSUE THREAD

**Issue by ivankhau** [blocknative/python-sdk#22]
### Current Behavior

{"transaction.input": "0x5932ead1", "_start": "true"} does not filter for prefix. 
eg input == "0x5932ead10000000000" does not match.

### Expected Behavior

Should match according to https://github.com/deitch/searchjs

### Steps To Reproduce

Set {"transaction.input": "0x5932ead1", "_start": "true"} as filter and then monitor.

### Python Version

3.9

### Relevant log output

```shell
N/A
```

### Anything else?

Tried all different syntax combination and nothing works.

**Comment by jac18281828** [comment]
I agree according to SearchJS documentation it appears your query is correct.   I tried a simple example here: https://gist.github.com/jac18281828/6b58d3d453d5341d29366ae290eee819

That seems to confirm it should work.   I'll have to investigate how it is behaving differently on the server side to cause this issue.   Right now I am out of the office because this weekend is a holiday in the United States.   I can do some digging next week though.

**Comment by jac18281828** [comment]
@ivankhau I believe the filter you are looking for would look something like this:

```
        filter = {
            'internalTransactions.input': '0x5932ead1',
            '_start': True
        }
```

I developed a complete working example in this gist:  https://gist.github.com/jac18281828/85b5153e0c18b1e086d08d6fc894ca89

I am closing out this ticket as I do not believe there is a bug here.   Feel free to reopen if you continue to have trouble.
